# Dependabot 配置

version: 2
updates:


  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "ci(deps)"

  # Docs (VitePress)
  - package-ecosystem: "npm"
    directory: "/docs"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "docs(deps)"
