# NetProxy Module Settings
# Switch on. Autostart service. (1=Enable, 0=Disable)
AUTO_START=1
# Outbound Mode (rule=Rules Distribute, global=Global Agent, direct=It's all straight.)
OUTBOUND_MODE=rule
# Node Selection Mode (manual=Manual Selection, urltest=Dynamic speed.)
SELECTOR_MODE=urltest
# GMS Repair (1=Enable, 0=Disable)
GMS_FIX=0
# Current Use sing-box Path to out-of-site configuration file
CURRENT_CONFIG="/data/adb/modules/netproxy/config/singbox/outbounds/default/default.json"
