name: Sync to KernelSU Repo

# Trigger condition
on:
  push:
    branches:
      - main
  release:
    types: [published]
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0 
          # Critical repairs: Ban checkout Plugin Takeover Git Evidence
          persist-credentials: false 

      - name: Sync Source Code and Tags
        env:
          DEST_REPO: "https://x-access-token:${{ secrets.SYNC_PAT }}@github.com/KernelSU-Modules-Repo/netproxy.git"
        run: |
          git remote add downstream "$DEST_REPO"
          
          git push downstream --all --force
          
          git push downstream --tags || true
          
          echo "Source is complete! The protected label has been bypassed."

      - name: Sync Latest Release
        # Only publish new Release Or run this step on manual trigger
        if: github.event_name == 'release' || github.event_name == 'workflow_dispatch'
        env:
          GH_TOKEN: ${{ secrets.SYNC_PAT }}
          UPSTREAM_REPO: ${{ github.repository }} # Current repository (Fanju6/NetProxy-Magisk)
          DEST_REPO: "KernelSU-Modules-Repo/netproxy" # Target warehouse
        run: |
          # 1. Get the main warehouse up to date Release tab name
          LATEST_TAG=$(gh release view --repo $UPSTREAM_REPO --json tagName -q .tagName)
          echo "Main repository update Release Label: $LATEST_TAG"
          
          # 2. Check if the downstream warehouse is already there. Release
          if gh release view $LATEST_TAG --repo $DEST_REPO &>/dev/null; then
            echo "An downstream warehouse already exists. Release $LATEST_TAG, no need to repeat sync."
          else
            echo "Missing downstream warehouse Release $LATEST_TAGOther Organiser..."
            
            # 3. Create a temporary directory and download all attachments from the main repository
            mkdir -p release_assets
            gh release download $LATEST_TAG --repo $UPSTREAM_REPO --dir release_assets
            
            # 4. Fetch main warehouse Release Title and update log
            TITLE=$(gh release view $LATEST_TAG --repo $UPSTREAM_REPO --json name -q .name)
            NOTES=$(gh release view $LATEST_TAG --repo $UPSTREAM_REPO --json body -q .body)
            
            # 5. Create the same in downstream warehouses Release Other Organiser
            gh release create $LATEST_TAG ./release_assets/* --repo $DEST_REPO --title "$TITLE" --notes "$NOTES"
            
            echo "Release $LATEST_TAG Synchronized!"
          fi
